# SPDX-FileCopyrightText: 2014-2023 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

---
resolutions:
  rule_violations:
  - message: "The package PyPI::certifi:.* has the declared ScanCode copyleft-limited categorized license MPL-2.0."
    reason: "DYNAMIC_LINKAGE_EXCEPTION"
    comment: "We are not modifying certifi and we dynamically link to it, so acording to MPL-2.0 this allows us to keep our code with a completely different license. In this kind of case, MPL-2.0 is not viral. https://www.mozilla.org/en-US/MPL/2.0/FAQ/"
  - message: "The package PyPI::.* has the declared ScanCode copyleft-limited categorized license LGPL.*"
    reason: "DYNAMIC_LINKAGE_EXCEPTION"
    comment: "This is not a problem because python modules are always dynamic, see https://stackoverflow.com/questions/8580223/using-python-module-on-lgpl-license-in-commercial-product and https://mail.python.org/pipermail/tutor/2015-June/105759.html."
